### ISSUE TITLE
How to convert 3dmm texture to flame texture?

### ISSUE THREAD

**Issue by code-conquer** [TimoBolkart/BFM_to_FLAME#11]
Hello, the code of this branch demonstrates how to convert 3dmm mesh into flame mesh, but there is no texture conversion. Do you know how to convert 3dmm texture into flame texture? Looking forward to your reply, thank you very much!

**Comment by code-conquer** [comment]
> Hello, the code of this branch demonstrates how to convert 3dmm mesh into flame mesh, but there is no texture conversion. Do you know how to convert 3dmm texture into flame texture? Looking forward to your reply, thank you very much!

For example, I want to convert the face texture map of bfm2009 into the texture map of flame

**Comment by TimoBolkart** [comment]
The problem with this is that the FLAME mesh covers regions that are not part of the BFM mesh (i.e., eyeballs, back of the head, neck, nostrils, mouth inside triangles). Trying to directly convert the BFM texture map to FLAME would cause poor results in this missing regions. This is, why we do some additional inpainting to the recovered textures.
