### ISSUE TITLE
Should we change the corresponding landmarks of bfm?

### ISSUE THREAD

**Issue by laceyliao** [TimoBolkart/BFM_to_FLAME#12]
Thank you for your code. I am a green hand in 3d face reconstruction, I wonder when converting a BFM mesh to a FLAME mesh, should we change the corresponding landmarks?

**Comment by TimoBolkart** [comment]
What do you mean with changing the corresponding landmarks? Do you mean having a similar landmark embedding for FLAME?

**Comment by TimoBolkart** [comment]
Closed due to inactivity
