### ISSUE TITLE
How to create "BFM_to_FLAME_corr.npz"

### ISSUE THREAD

**Issue by Agent-INF** [TimoBolkart/BFM_to_FLAME#2]
Thanks for the great work!
Although you directly provided the file "BFM_to_FLAME_corr.npz", I am curious how this file was generated, and it seems not mentioned in the code.
Suppose, I want to convert other BFM-like models to FLAME, or convert BFM to other FLAME-like models, then what should I do?

**Comment by TimoBolkart** [comment]
The cache_data() in col_to_tex.py  was used to create the BFM_to_FLAME_corr.npz data. However this requires tightly aligned meshes in different topology in order to compute that

**Comment by enjoybo** [comment]
Hi Timo,
Great work to fit BFM with FLAME. Could you please share the tightly aligned meshes showed in col_to_tex.py: "./data/BFM_aligned.obj" and "./data/FLAME_uv_template.obj"? I want to refer to how tight the two meshes need to be aligned before fitting then I could convert other BFM-like models to FLAME this way. Thanks.

**Comment by TimoBolkart** [comment]
I am not sure if I can share meshes in BFM topology. I general, you could also add a feature request if you have a particular model in mind. Maybe we can provide the conversion for these other models as well.
