### ISSUE TITLE
Regarding the obj file

### ISSUE THREAD

**Issue by hjo111** [TimoBolkart/BFM_to_FLAME#21]
Hello, thanks for the share.
I can't fit my scan data to flame

umm.. in mesh_convert.py 
my scan file is return ('Conversion failed - input mesh does not match any setup')
my scan file 
BFM_mesh.v.shape[0] = 115676
BFM_mesh.f.shape[0] = 229432

Can't it be executed except when the if statement is satisfied?

Thanks for your advice..

**Comment by TimoBolkart** [comment]
Hi, what exactly are you trying to do? The code is designed to convert meshes in Basel Face Model (BFM) mesh topology to FLAME meshes. The script supports different BFM version, but it does not support arbitrary scans if this is what you are trying to do. If you are trying to convert arbitrary scans to FLAME (i.e., by fitting FLAME to the scan), you can have a look at the fit_scan demo of the[ flame-fitting repository](https://github.com/Rubikplayer/flame-fitting) .
