### ISSUE TITLE
Albedo model

### ISSUE THREAD

**Issue by mohamad-hasan-sohan-ajini** [TimoBolkart/BFM_to_FLAME#24]
Hey

It'll be appreciated if `FLAME_albedo_from_BFM.npz` file be available. I believe it saves some efforts.

Regards

**Comment by TimoBolkart** [comment]
Hi, the purpose of the `python col_to_tex.py` is to build the `FLAME_albedo_from_BFM.npz`. The BFM lincense does not permit sharing the model, so we cannot directly make the converted albedo space for FLAME available.
