### ISSUE TITLE
Replace BFM with FLAME?

### ISSUE THREAD

**Issue by emlcpfx** [TimoBolkart/BFM_to_FLAME#25]
@TimoBolkart Do you know someone I could hire who could help me take any usage of the BFM out of 3DDFA_v2, and replace it with the FLAME model instead?

**Comment by TimoBolkart** [comment]
Hey, unfortunately I don't know anybody with free capacity to help with that. Instead of trying to replace BFM in 3DDFA_V2, you could look into [EMOCA](https://github.com/radekd91/emoca) or other FLAME-bases methods, which are listed [here](https://github.com/TimoBolkart/FLAME-Universe).

**Comment by emlcpfx** [comment]
Thank you for the answer! I wasn’t able to achieve the same level of temporal stability in videos with EMOCA as 3DDFA_V2.

I’ll look further into the link you sent. 👍

**Comment by TimoBolkart** [comment]
Did you try EMOCA v2? The problem could be the preprocessing using face detectiom in EMOCA, improving the stability of the face crops gives a more stable prediction
