### ISSUE TITLE
cannot download impainting masks 

### ISSUE THREAD

**Issue by lkh9908** [TimoBolkart/BFM_to_FLAME#4]
Thank you for the great work! The link to download impainting masks is not working. Can you kindly solve that?

**Comment by TimoBolkart** [comment]
The download link should be working again

**Comment by heyoon01** [comment]
It's not working. Can you please take a look?

**Comment by TimoBolkart** [comment]
I just tried and it worked for me. What is the problem?

**Comment by heyoon01** [comment]
That's odd. I don't get any files downloaded nor get redirected to another page. However I got the file by entering the full address...
