### ISSUE TITLE
The FLAME_albedo_from_BFM.npz seems to be wrong?

### ISSUE THREAD

**Issue by UestcJay** [TimoBolkart/BFM_to_FLAME#5]
Thanks for your great work. I followed the instructions to generate the file, but the data in it seems to be wrong . all are zeros. I tried it twice. Can you help me?

**Comment by TimoBolkart** [comment]
Hi, what do you mean with all data seems to be zero? All entries in the resulting file are zero? Or the file is zero size? Can you share the resulting file, then we can have a look.

**Comment by UestcJay** [comment]
Thank you for your reply, my carelessness caused this problem. Here is another question as mentioned in [here](https://github.com/YadiraF/DECA/issues/32), can you give me some help

**Comment by TimoBolkart** [comment]
It seems that your question got answered meanwhile
