### ISSUE TITLE
FLAME_to_BFM

### ISSUE THREAD

**Issue by taylorlu** [TimoBolkart/BFM_to_FLAME#6]
This work provides a way to convert BFM model to FLAME, but any plan to demonstrate:
1. how to create a BFM texture model from the FLAME vertex color space, and
2. how to convert a FLAME mesh to a BFM mesh.

Thanks in advance.

**Comment by TimoBolkart** [comment]
BFM does not support all expressions and jaw poses that FLAME is able to do, and the BFM identity shape variations are more constrained. Going from FLAME to BFM easily causes artifacts, that's why we do not support this direction.

**Comment by taylorlu** [comment]
Thanks for your reply.
