### ISSUE TITLE
inpainting masks not available

### ISSUE THREAD

**Issue by linchaobao** [TimoBolkart/BFM_to_FLAME#9]
Would you please check why the inpainting masks are not available for download? Thanks!

**Comment by TimoBolkart** [comment]
Can you please try again? I just checked at it works.

**Comment by JANVI2411** [comment]
> Would you please check why the inpainting masks are not available for download? Thanks!

I'm facing the same issue. @TimoBolkart can you please check out again?

**Comment by Zenway-Wong** [comment]
> > Would you please check why the inpainting masks are not available for download? Thanks!
> 
> I'm facing the same issue. @TimoBolkart can you please check out again?

I just tried to download the file by clicking the link in windows, it didn't work. 

You can try **wget** in linux. I download it successfully!

**Comment by leslie-ds** [comment]
Would you please check why the inpainting masks are not available for download

**Comment by TimoBolkart** [comment]
Please try again, there was a problem with our file server which is fixed now. I tried downloading from a Linux environment using FF browser works.

**Comment by liuheng92** [comment]
> > > Would you please check why the inpainting masks are not available for download? Thanks!
> > 
> > 
> > I'm facing the same issue. @TimoBolkart can you please check out again?
> 
> I just tried to download the file by clicking the link in windows, it didn't work.
> 
> You can try **wget** in linux. I download it successfully!

this solution will be ok!
